server:
  session-timeout: 1800
  port: 9000
spring:
#  thymeleaf:
#    mode: LEGACYHTML5
#    cache: false
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
#  servlet:
#    multipart:
#      max-file-size: 30Mb
#      max-request-size: 30Mb
#  devtools:
#    restart:
#      enabled: true
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:config/ehcache.xml
mybatis:
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
#  typeAliasesPackage: com.bootdo.**.domain
