
# 打印sql
logging:
  level:
    com.example: info
  file: my.log
spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.0.252/MapLayerBoot?allowMultiQueries=true&charSet=UTF-8
    url: jdbc:postgresql://localhost/GeoTest?allowMultiQueries=true&charSet=UTF-8
#    url: jdbc:postgresql://localhost/MapLayerBoot?allowMultiQueries=true&charSet=UTF-8

    username: postgres
#    password: here940901940901
    password: postgres940901
    initialSize: 1 
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
